export enum ConfigurableView {
  FIELD_VIEW,
  GRAPH_VIEW,
  CONFIG_VIEW,
  TELEMETRY_VIEW,
  HARDWARE_VIEW,
  RECORDER_VIEW,
  CAMERA_VIEW,
  OPMODE_VIEW,
  LOGGING_VIEW,
  HARDWARE_CONFIG_VIEW,
  ERROR_VIEW,
}
